//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace MyBilling
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Companydetail>();
                db.CreateTable<entry>();
                db.CreateTable<entrydetail>();
                db.CreateTable<registercompany>();
                db.CreateTable<user>();
                db.CreateTable<usertype>();
            }
        }
    }
    public partial class Companydetail
    {
        [PrimaryKey]
        public Int64 Companyid { get; set; }
        
        [MaxLength(100)]
        [NotNull]
        public String Name { get; set; }
        
        [MaxLength(1000)]
        public String Add1 { get; set; }
        
        [MaxLength(1000)]
        public String Add2 { get; set; }
        
        [MaxLength(1000)]
        public String Add3 { get; set; }
        
        [MaxLength(100)]
        public String City { get; set; }
        
        [MaxLength(1000)]
        public String vattinno { get; set; }
        
    }
    
    public partial class entry
    {
        [PrimaryKey]
        public Int64 entryid { get; set; }
        
        [NotNull]
        public DateTime date { get; set; }
        
        [MaxLength(100)]
        [NotNull]
        public String userid { get; set; }
        
        [NotNull]
        public Int64 regcompanyid { get; set; }
        
    }
    
    public partial class entrydetail
    {
        [PrimaryKey]
        public Int64 entrydetailid { get; set; }
        
        [NotNull]
        public Int64 entryid { get; set; }
        
        [MaxLength(100)]
        [NotNull]
        public String vehicleid { get; set; }
        
        [MaxLength(100)]
        [NotNull]
        public String itemname { get; set; }
        
        [NotNull]
        public Decimal rate { get; set; }
        
        [NotNull]
        public Decimal amount { get; set; }
        
        [NotNull]
        public Decimal quantity { get; set; }
        
    }
    
    public partial class registercompany
    {
        [PrimaryKey]
        public Int64 CompanyId { get; set; }
        
        [MaxLength(1000)]
        [NotNull]
        public String Name { get; set; }
        
        [MaxLength(1000)]
        [NotNull]
        public String Add1 { get; set; }
        
        [MaxLength(1000)]
        [NotNull]
        public String Add2 { get; set; }
        
        [MaxLength(1000)]
        [NotNull]
        public String Add3 { get; set; }
        
        [MaxLength(100)]
        [NotNull]
        public String City { get; set; }
        
    }
    
    public partial class user
    {
        [PrimaryKey]
        [MaxLength(100)]
        public String userid { get; set; }
        
        [MaxLength(100)]
        [NotNull]
        public String password { get; set; }
        
        [NotNull]
        public Int32 usertypeid { get; set; }
        
    }
    
    public partial class usertype
    {
        [PrimaryKey]
        public Int64 typeid { get; set; }
        
        [MaxLength(100)]
        [NotNull]
        public String typename { get; set; }
        
    }
    
}
